version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER : myuser
      POSTGRES_PASSWORD : mypassword
      POSTGRES_DB : mydatabase
    ports:
      - "5432:5432"
    
  dotnet_rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
#  dotnet_minio:
#    image: minio/minio:latest
   
#  dotnet_mongodb:
#    image: mongo:latest
    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    environment:
      ConnectionStrings__Default: Server=localhost;Port=5433;Database=mydatabase;User Id=myuser;Password=mypassword;      
    image: dotnet-web
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
    
  dotnet_mailing:
    image: dotnet-web
    build:
      context: .
      dockerfile: "Dotnet.Homeworks.Mailing.API/Dockerfile"
    environment:
      EmailConfig__Host: rmuser
      EmailConfig__Password: rmpassword
      EmailConfig__Email: rmpassword
      EmailConfig__Port: rmpassword
    ports:
      - "8000:80"
    depends_on:
      - dotnet_rabbitmq
    
#  dotnet_storage:
#    image: dotnet-web